# Extra information for packages that are in repology, but haven't used the sources we used (or were otherwise skipped from the dump extract)

[ampl-asl]
url_patterns = ["^\\Qhttp://netlib.org/ampl/solvers.tgz\\E()$"] # No versioning info available

[epoll-shim]
repositories = ["https://github.com/jiixyj/epoll-shim.git"]

[expat]
url_patterns = ["^\\Qhttps://github.com/libexpat/libexpat/releases/download/R\\E[^/]+\\Q/expat-\\E(\\d.*)\\Q.tar.xz\\E$"]

[fftw]
url_patterns = ["^\\Qhttp://fftw.org/~stevenj/fftw-\\E(\\d.*)\\Q.tar.gz\\E$"]

[gr]
repositories = ["https://github.com/sciapp/gr.git"]

[git]
url_patterns = ["^\\Qhttps://github.com/git-for-windows/git/releases/download/v\\E(\\d.*)\\Q.windows.1/Git-\\E\\1\\Q-64-bit.tar.bz2\\E$"]

[git-for-windows]
url_patterns = ["^\\Qhttps://github.com/git-for-windows/git/releases/download/v\\E(\\d.*)\\Q/Git-\\E.+\\Q-64-bit.tar.bz2\\E$"]

[glib]
url_patterns = ["^\\Qhttps://ftp.gnome.org/pub/gnome/sources/glib/\\E[^/]+\\Q/glib-\\E(\\d.*)\\Q.tar.xz\\E$"]

[kaleido]
repositories = ["https://github.com/plotly/Kaleido.git"]
url_patterns = ["^\\Qhttps://github.com/plotly/Kaleido/releases/download/v\\E(\\d.*)\\Q/kaleido_"]

[lerc]
repositories = ["https://github.com/Esri/lerc"]
url_patterns = ["^\\Qhttps://github.com/Esri/lerc/archive/refs/tags/v\\E(\\d.*)\\Q.tar.gz\\E$"]

[libblastrampoline]
repositories = ["https://github.com/JuliaLinearAlgebra/libblastrampoline.git", "https://github.com/staticfloat/libblastrampoline"]

[libevdev]
repositories = ["https://gitlab.freedesktop.org/libevdev/libevdev"]

[libpng]
url_patterns = [
    "^\\Qhttps://sourceforge.net/projects/libpng/files/libpng\\E\\d+/([^/]+)/",
    "^\\Qhttps://downloads.sourceforge.net/libpng/libpng-\\E(\\d.*)\\Q.tar\\E",
    "^\\Qftp://ftp.simplesystems.org/pub/libpng/png/src/history/libpng\\E\\d+/libpng-(.+)\\Q.tar\\E",
    "^\\Qhttps://vorboss.dl.sourceforge.net/project/libpng/libpng\\E\\d+/([^/]+)/",
]

[llvm-openmp]
url_patterns = ["^\\Qhttps://github.com/llvm/llvm-project/releases/download/llvmorg-\\E(\\d.*)\\Q/openmp-\\E\\1\\Q.src.tar.xz\\E$"]

[mbedtls]
repositories = ["https://github.com/ARMmbed/mbedtls.git"]

[openspecfun]
repositories = ["https://github.com/JuliaMath/openspecfun.git"]
url_patterns = ["^\\Qhttps://github.com/JuliaMath/openspecfun/archive/v\\E(\\d.*)\\Q.tar.gz\\E$"]

[suitesparse]
repositories = ["https://github.com/DrTimothyAldenDavis/SuiteSparse.git", "https://github.com/Wimmerer/SuiteSparse.git"]

[spral]
repositories = ["https://github.com/ralna/spral.git"]

[tracy]
repositories = ["https://github.com/wolfpld/tracy.git"]

# NOT IN REPOLOGY:
[intel-openmp]
url_patterns = [
    "^\\Qhttps://files.pythonhosted.org/packages/\\E[^/]+/[^/]+/[^/]+/intel_openmp-(.+)-py",
    "^\\Qhttps://anaconda.org/intel/intel-openmp/\\E[^/]+/download/[^/]+/intel-openmp-(.+)-intel",
    "^\\Qhttps://anaconda.org/intel/openmp/\\E[^/]+/download/[^/]+/openmp-(.+)-intel",
    "^\\Qhttps://conda.anaconda.org/intel/\\E[^/]+/intel-openmp-(.+)-intel",
    "^\\Qhttps://software.repos.intel.com/python/conda/\\E[^/]+/intel-openmp-(.+)-intel",
]
cpes = ["intel:openmp"]

[llvm-extra]
repositories = ['https://github.com/JuliaLLVM/LLVM.jl', 'https://github.com/maleadt/LLVM.jl.git', 'https://github.com/vchuravy/LLVMExtra.git']

# QT is overzealously merged into one package on repology
[qtbase]
url_patterns = ["^\\Qhttps://download.qt.io/official_releases/qt/\\E[^/]+/(.+)\\Q/submodules/qtbase-\\E"]
cpes = ["qt:qtbase"]

[qt]
url_patterns = ["^\\Qhttps://download.qt.io/official_releases/qt/\\E[^/]+/(.+)\\Q/single/qt-\\E"]
cpes = ["qt:qt"]

[qtshadertools]
url_patterns = ["^\\Qhttps://download.qt.io/official_releases/qt/\\E[^/]+/(.+)\\Q/submodules/qtshadertools-\\E"]

[qtdeclarative]
url_patterns = ["^\\Qhttps://download.qt.io/official_releases/qt/\\E[^/]+/(.+)\\Q/submodules/qtdeclarative-\\E"]

[qtwayland]
url_patterns = ["^\\Qhttps://download.qt.io/official_releases/qt/\\E[^/]+/(.+)\\Q/submodules/qtwayland-"]

[rmath-julia]
repositories = ["https://github.com/JuliaStats/Rmath-julia.git"]
url_patterns = ["^\\Qhttps://github.com/JuliaStats/Rmath-julia/archive/v\\E(\\d.*)\\Q.tar.gz\\E$"]

