[libpng]
url_regexes = [
    'https://sourceforge\.net/projects/libpng/files/libpng\d+/([^/]+)/',
    'https://downloads\.sourceforge\.net/libpng/libpng-(.+)\.tar',
    'ftp://ftp\.simplesystems\.org/pub/libpng/png/src/history/libpng\d+/libpng-(.+)\.tar',
    'https://vorboss\.dl\.sourceforge\.net/project/libpng/libpng\d+/([^/]+)/',
]
cpe = "cpe:2.3:a:libpng:libpng"

[libssh2]
url_regexes = [
    'https://github\.com/libssh2/libssh2/releases/download/libssh2-([^/]+)/',
]
cpe = "cpe:2.3:a:libssh2:libssh2"

[OpenBLAS]
url_regexes = [
    'https://github\.com/(?:xianyi|OpenMathLib)/OpenBLAS/releases/download/v([^/]+)/',
    'https://github\.com/xianyi/OpenBLAS/archive/v(.+)\.tar',
]
cpe = "cpe:2.3:a:openblas_project:openblas"
vendors = ["openblas", "openblas_project", "xianyi"]

[openssl]
url_regexes = [
    'https://github\.com/openssl/openssl/releases/download/openssl-([^/]+)/',
    'https://www\.openssl\.org/source/openssl-(.+)\.tar',
]
cpe = "cpe:2.3:a:openssl:openssl"

[cairo]
repo = "https://gitlab.freedesktop.org/cairo/cairo.git"
url_regexes = [
    'https://(?:www\.)?cairographics\.org/releases/cairo-(.+)\.tar',
]
cpe = "cpe:2.3:a:cairographics:cairo"

[fontconfig]
url_regexes = [
    'https://gitlab\.freedesktop\.org/api/v\d+/projects/\d+/packages/generic/fontconfig/[^/]+/fontconfig-(.+)\.tar',
    'https?://www\.freedesktop\.org/software/fontconfig/release/fontconfig-(.+)\.tar',
]
cpe = "cpe:2.3:a:fontconfig_project:fontconfig"
vendors = ["fontconfig", "freedesktop"]

[freetype]
url_regexes = [
    'https?://download\.savannah\.gnu\.org/releases/freetype/freetype-(.+)\.tar'
]
cpe = "cpe:2.3:a:freetype:freetype"

[glib]
url_regexes = [
    'https://ftp\.gnome\.org/pub/gnome/sources/glib/[^/]+/glib-(.+)\.tar',
]
cpe = "cpe:2.3:a:gnome:glib"

[lzo]
url_regexes = [
    'https://www\.oberhumer\.com/opensource/lzo/download/lzo-(.+).tar'
]
cpe = "cpe:2.3:a:lzo_project:lzo"

[pixman]
url_regexes = [
    'https?://www\.cairographics\.org/releases/pixman-(.+)\.tar',
]
cpe = "cpe:2.3:a:pixman:pixman"

[zlib]
repo = 'https://github.com/madler/zlib.git'
url_regexes = [
    'https?://zlib\.net/zlib-(.+)\.tar',
]
cpe = "cpe:2.3:a:zlib:zlib"

[IntelOpenMP]
url_regexes = [
    'https://files\.pythonhosted\.org/packages/[^/]+/[^/]+/[^/]+/intel_openmp-(.+)-py',
    'https://anaconda\.org/intel/intel-openmp/[^/]+/download/[^/]+/intel-openmp-(.+)-intel',
    'https://anaconda\.org/intel/openmp/[^/]+/download/[^/]+/openmp-(.+)-intel',
    'https://conda\.anaconda\.org/intel/[^/]+/intel-openmp-(.+)-intel',
    'https://software\.repos\.intel\.com/python/conda/[^/]+/intel-openmp-(.+)-intel',
]
cpe = "cpe:2.3:a:intel:openmp"

[LLVMOpenMP]
url_regexes = [
    'https://github.com/llvm/llvm-project/releases/download/llvmorg-[^/]+/openmp-(.+)\.src'
]

[ffmpeg]
url_regexes = [
    'https://ffmpeg\.org/releases/ffmpeg-(.+).tar',
]
cpe = "cpe:2.3:a:ffmpeg:ffmpeg"

[LAME]
url_regexes = [
    'https://downloads\.sourceforge\.net/project/lame/lame/[^/]+/lame-(.+).tar',
    'https://downloads\.sourceforge\.net/lame/lame-(.+)\.tar',
]
cpe = "cpe:2.3:a:lame_project:lame"

[fribidi]
repo = 'https://github.com/fribidi/fribidi.git'
url_regexes = [
    'https://github\.com/fribidi/fribidi/releases/download/v(.+)/fribidi-',
]
cpe = "cpe:2.3:a:gnu:fribidi"

# # URI("https?://www.cairographics.org/releases/pixman-0.28.2.tar.gz") => pixman,
# # URI("https?://ftp.gnu.org/pub/gnu/gettext/gettext-0.18.2.tar.gz") => gettext,
# # URI("ftp://sourceware.org/pub/libffi/libffi-3.0.11.tar.gz") => libffi,
# # URI("https?://ftp.gnome.org/pub/gnome/sources/glib/2.34/glib-2.34.3.tar.xz") => gobject,
# # URI("https?://ftp.gnome.org/pub/GNOME/sources/pango/1.32/pango-1.32.6.tar.xz") => [pango,pangocairo],

[pcre2]
url_regexes = [
    'https://github\.com/PCRE2Project/pcre2/releases/download/pcre2-[^/]+/pcre2-(.+)\.tar',
    'https://ftp\.pcre\.org/pub/pcre/pcre2-(.+)\.tar',
]
repo = 'https://github.com/PCRE2Project/pcre2'
cpe = "cpe:2.3:a:pcre:pcre2"

[libaom]
url_regexes = [
     'https://storage\.googleapis\.com/aom-releases/libaom-(.+)\.tar',
]
cpe = "cpe:2.3:a:aomedia:aomedia"

[libass]
url_regexes = [
    'https://github\.com/libass/libass/releases/download/[^/]+/libass-(.+)\.tar',
]
cpe = "cpe:2.3:a:libass_project:libass"

[fdkaac]
url_regexes = [
    'https://downloads\.sourceforge\.net/project/opencore-amr/fdk-aac/fdk-aac-(.+)\.tar',
    'https://downloads\.sourceforge\.net/opencore-amr/fdk-aac-(.+)\.tar'
]
cpe = "cpe:2.3:a:fdkaac_project:fdkaac"
vendors = ["opencore-amr", "fdkaac_project", "fdkaac"]

[libvorbis]
url_regexes = [
    'https://ftp\.osuosl\.org/pub/xiph/releases/vorbis/libvorbis-(.+)\.tar',
    'https://downloads\.xiph\.org/releases/vorbis/libvorbis-(.+)\.tar'
]
cpe = "cpe:2.3:a:xiph.org:libvorbis"
vendors = ["xiph", "xiph.org"]

[x265]
url_regexes = [
    'https://bitbucket\.org/multicoreware/x265_git/get/Release_(.+)\.tar',
    'http://ftp\.videolan\.org/pub/videolan/x265/x265_(.+)\.tar'
]
repo = 'https://bitbucket.org/multicoreware/x265_git.git'
cpe = "cpe:2.3:a:multicorewareinc:x265"

[graphite2]
url_regexes = [
    'https://github\.com/silnrsi/graphite/releases/download/[^/]+/graphite2-(.+)\.t',
]
cpe = "cpe:2.3:a:sil:graphite2"

[harfbuzz]
url_regexes = [
    'https://github\.com/harfbuzz/harfbuzz/releases/download/[^/]+/harfbuzz-(.+)\.t',
    'https://www\.freedesktop\.org/software/harfbuzz/release/harfbuzz-(.+)\.t',
]
cpe = "cpe:2.3:a:harfbuzz_project:harfbuzz"

[curl]
url_regexes = [
    'https://curl\.se/download/curl-(.+)\.t',
    'https://curl\.haxx\.se/download/curl-(.+)\.t',
]
cpe = "cpe:2.3:a:curl_project:curl"
vendors = ["curl", "haxx"]

[libgit2]
repo = 'https://github.com/libgit2/libgit2.git'
cpe = "cpe:2.3:a:libgit2:libgit2"

[git]
url_regexes = [
    'https://mirrors\.edge\.kernel\.org/pub/software/scm/git/git-(.+)\.tar',
    'https://github\.com/git-for-windows/git/releases/download/v(.+)\.windows',
]
cpe = "cpe:2.3:a:git-scm:git"
vendors = ["git", "git-scm"]

[git-for-windows]
url_regexes = [
    'https://github\.com/git-for-windows/git/releases/download/v(.+)/Git-',
]
cpe = "cpe:2.3:a:git_for_windows_project:git_for_windows"

[libffi]
url_regexes = [
    'https://sourceware\.org/pub/libffi/libffi-(.+)\.tar',
    'https://github\.com/libffi/libffi/releases/download/v([^/]+)/'
]
cpe = "cpe:2.3:a:libffi_project:libffi"

[libtiff]
url_regexes = [
    'https://download\.osgeo\.org/libtiff/tiff-(.+)\.tar',
]
cpe = "cpe:2.3:a:libtiff:libtiff"

[util-linux]
url_regexes = [
    'https://mirrors\.edge\.kernel\.org/pub/linux/utils/util-linux/v(.+)/util-linux'
]
cpe = "cpe:2.3:a:kernel:util-linux"

[mbed_tls]
repo = 'https://github.com/Mbed-TLS/mbedtls.git'
repos = ['https://github.com/ARMmbed/mbedtls.git']
cpe = "cpe:2.3:a:arm:mbed_tls"

[pango]
url_regexes = [
    'http://ftp\.gnome\.org/pub/GNOME/sources/pango/[^/]+/pango-(.+)\.tar',
]
cpe = "cpe:2.3:a:gnome:pango"

[qtbase]
url_regexes = [
    'https://download\.qt\.io/official_releases/qt/[^/]+/(.+)/submodules/qtbase-',
]
cpe = "cpe:2.3:a:qt:qtbase"

[qt]
url_regexes = [
    'https://download\.qt\.io/official_releases/qt/[^/]+/(.+)/single/qt-',
]
cpe = "cpe:2.3:a:qt:qt"

[qtshadertools]
url_regexes = [
    'https://download\.qt\.io/official_releases/qt/[^/]+/(.+)/submodules/qtshadertools-'
]

[qtdeclarative]
url_regexes = [
    'https://download\.qt\.io/official_releases/qt/[^/]+/(.+)/submodules/qtdeclarative-'
]

[qtwayland]
url_regexes = [
    'https://download\.qt\.io/official_releases/qt/[^/]+/(.+)/submodules/qtwayland-'
]


[rclone]
repo = 'https://github.com/rclone/rclone.git'
url_regexes = [
    'https://github\.com/rclone/rclone/releases/download/v(.+)/rclone-',
]
cpe = "cpe:2.3:a:rclone:rclone"

[wayland]
url_regexes = [
    'https://wayland\.freedesktop\.org/releases/wayland-(\d.+)\.tar',
    'https://gitlab\.freedesktop\.org/wayland/wayland/-/releases/[^/]+/downloads/wayland-(\d.+)\.tar',
]
cpe = "cpe:2.3:a:wayland:wayland"

[xz]
repo = 'https://github.com/tukaani-project/xz'
repos = ['https://git.tukaani.org/xz.git']
url_regexes = [
    'https://tukaani\.org/xz/xz-(.+)\.tar',
    'https://tukaani\.org/xz/xz-(.+)-windows\.',
    'https://github\.com/tukaani-project/xz/releases/download/v(.+)/xz',
]
cpe = "cpe:2.3:a:xz_project:xz"

[libICE]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libICE-(\d.+)\.tar']
cpe = "cpe:2.3:a:freedesktop:libice"
vendors = ["x", "x.org", "freedesktop"]

[dbus]
url_regexes = ['https://dbus\.freedesktop\.org/releases/dbus/dbus-(\d.+)\.tar']
cpe = "cpe:2.3:a:freedesktop:dbus"
vendors = ["x", "x.org", "freedesktop"]

[libX11]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libX11-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libx11"
vendors = ["x", "x.org", "freedesktop"]

[libxcursor]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXcursor-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxcursor"
vendors = ["x", "x.org", "freedesktop"]

[libxdmcp]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXdmcp-(\d.+)\.tar']
cpe = "cpe:2.3:a:x.org:libxdmcp"
vendors = ["x", "x.org", "freedesktop"]

[libxfixes]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXfixes-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxfixes"
vendors = ["x", "x.org", "freedesktop"]

[libXi]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXi-(\d.+)\.tar']
cpe = "cpe:2.3:a:x.org:libxi"
vendors = ["x", "x.org", "freedesktop"]

[libXinerama]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXinerama-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxinerama"
vendors = ["x", "x.org", "freedesktop"]

[libXrandr]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXrandr-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxrandr"
vendors = ["x", "x.org", "freedesktop"]

[libxcb]
url_regexes = ['https://www\.x\.org/archive/individual/xcb/libxcb-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxcb"
vendors = ["x", "x.org", "freedesktop"]

[libXext]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXext-(\d.+)\.tar']
cpe = "cpe:2.3:a:x:libxext"
vendors = ["x", "x.org", "freedesktop"]

[libSM]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libSM-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libXau]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXau-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[xkbcomp]
url_regexes = ['https://www\.x\.org/archive/individual/app/xkbcomp-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[xkeyboard-config]
url_regexes = ['https://www\.x\.org/archive/individual/data/xkeyboard-config/xkeyboard-config-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[xtrans]
url_regexes = ['https://www\.x\.org/archive/individual/lib/xtrans-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxkbfile]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libxkbfile-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util-cursor]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-cursor-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util-image]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-image-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util-keysyms]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-keysyms-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util-renderutil]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-renderutil-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxcb-util-wm]
url_regexes = ['https://xcb\.freedesktop\.org/dist/xcb-util-wm-(\d.+)\.tar']
vendors = ["x", "x.org", "freedesktop"]

[libxrender]
url_regexes = ['https://www\.x\.org/archive/individual/lib/libXrender-(.+)\.tar']
cpe = "cpe:2.3:a:x.org:libxrender"
vendors = ["x", "x.org", "freedesktop"]

[libinput]
repo = 'https://gitlab.freedesktop.org/libinput/libinput'
cpe = "cpe:2.3:a:freedesktop:libinput"
vendors = ["x", "x.org", "freedesktop"]

[xkbcommon]
repo = 'https://github.com/xkbcommon/libxkbcommon'
url_regexes = ['https://xkbcommon\.org/download/libxkbcommon-(.+)\.tar']
cpe = "cpe:2.3:a:xkbcommon_project:xkbcommon"

[zstd_jl]
url_regexes = ['https://github\.com/facebook/zstd/releases/download/v(.+)/zstd-']
cpe = "cpe:2.3:a:facebook:zstandard"

[nghttp2]
repo = 'https://github.com/nghttp2/nghttp2.git'
url_regexes = ['https://github\.com/nghttp2/nghttp2/releases/download/v(.+)/nghttp2-']
cpe = "cpe:2.3:a:nghttp2:nghttp2"

[opus]
repo = 'https://github.com/xiph/opus.git'
repos = ['https://gitlab.xiph.org/xiph/opus']
url_regexes = ['https://archive\.mozilla\.org/pub/opus/opus-(.+)\.tar']
cpe = "cpe:2.3:a:xiph:opusfile"

[GDAL]
repo = 'https://github.com/OSGeo/gdal.git'
url_regexes = [
    'https://github\.com/OSGeo/gdal/releases/download/v(.+)/gdal-',
]
cpe = 'cpe:2.3:a:osgeo:gdal'

[NetCDF]
repo = 'https://github.com/Unidata/netcdf-c.git'
url_regexes = [
    'https://github\.com/Unidata/netcdf-fortran/archive/refs/tags/v(.+)\.tar',
    'https://github\.com/Unidata/netcdf-c/archive/v(.+)\.zip',
    'https://downloads\.unidata\.ucar\.edu/netcdf-c/(.+)/netcdf-c-',
    'https://downloads\.unidata\.ucar\.edu/netcdf-fortran/(.+)/netcdf-fortran-',
]

[p7zip]
repo = 'https://github.com/p7zip-project/p7zip'
url_regexes = [
    'https://downloads\.sourceforge\.net/project/p7zip/p7zip/(.+)/p7zip',
    'https://github\.com/jinfeihan57/p7zip/archive/refs/tags/v(.*)\.tar',
]
cpe = "cpe:2.3:a:7-zip:p7zip"

[7-zip]
url_regexes = [
    'https://downloads\.sourceforge\.net/project/sevenzip/7-Zip/(.+)/7z',
]
cpe = 'cpe:2.3:a:7-zip:7-zip'

[bzip2]
repo = 'https://github.com/enthought/bzip2-1.0.6.git'
repos = ['git://sourceware.org/git/bzip2.git']
cpe = 'cpe:2.3:a:bzip2_project:bzip2'

[epoll-shim]
repo = 'https://github.com/jiixyj/epoll-shim.git'

[libexpat]
url_regexes = [
    'https://github\.com/libexpat/libexpat/releases/download/[^/]+/expat-(.+)\.tar',
]
cpe = 'cpe:2.3:a:libexpat_project:libexpat'

[FFTW]
url_regexes = [
    'http://fftw\.org/~stevenj/fftw-(.+)\.tar',
    'http://fftw\.org/fftw-(.+)\.tar',
]

[GLFW]
url_regexes = [
    'https://github\.com/glfw/glfw/releases/download/(.+)/glfw-',
]

[GR]
repo = 'https://github.com/sciapp/gr.git'
url_regexes = [
    'https://github.com/sciapp/gr/releases/download/v(.+)/gr-',
]

[gettext]
url_regexes = [
    'https://ftp\.gnu\.org/pub/gnu/gettext/gettext-(.+)\.tar',
    'http://mirrors\.kernel\.org/gnu/gettext/gettext-(.+)\.tar,'
]
cpe = 'cpe:2.3:a:gnu:gettext'

[hwloc]
url_regexes = [
    'https://download\.open-mpi\.org/release/hwloc/[^/]+/hwloc-(.+)\.tar'
]
cpe = 'cpe:2.3:a:open-mpi:hwloc'

[Ipopt]
repo = 'https://github.com/coin-or/Ipopt.git'
url_regexes = [
    'https://github\.com/coin-or/Ipopt/archive/releases/(.+)\.tar'

]

[libjpeg-turbo]
repo = 'https://github.com/libjpeg-turbo/libjpeg-turbo.git'
url_regexes = [
    'https://github\.com/libjpeg-turbo/libjpeg-turbo/archive/(.+)\.tar',
    'https://github\.com/libjpeg-turbo/libjpeg-turbo/releases/download/(.+)/libjpeg-turbo',
]

[Kaleido]
repo = 'https://github.com/plotly/Kaleido.git'
url_regexes = [
    'https://github\.com/plotly/Kaleido/releases/download/v(.+)/kaleido_',
]

[libLerc]
repo = 'https://github.com/Esri/lerc'
url_regexes = [
    'https://github\.com/Esri/lerc/archive/refs/tags/v(.+)\.tar',
]

[LLVMExtra]
repo = 'https://github.com/JuliaLLVM/LLVM.jl'
repos = ['https://github.com/maleadt/LLVM.jl.git', 'https://github.com/vchuravy/LLVMExtra.git']

[Lbfgsb]
url_regexes = ['http://users\.iems\.northwestern\.edu/~nocedal/Software/Lbfgsb\.(.+)\.tar']

[tracy]
repo = 'https://github.com/wolfpld/tracy.git'
url_regexes = [
    'https://github\.com/wolfpld/tracy/archive/refs/tags/v(.+)\.tar',
]

[libglvnd]
url_regexes = [
    'https://github\.com/NVIDIA/libglvnd/releases/download/v(.+)/libglvnd-',
    'https://gitlab\.freedesktop\.org/glvnd/libglvnd/-/archive/v(.+)/libglvnd-',
    'https://gitlab\.freedesktop\.org/glvnd/libglvnd/uploads/[^/]+/libglvnd-(.+)\.tar'
]

[libiconv]
url_regexes = [
    'https://ftp\.gnu\.org/pub/gnu/libiconv/libiconv-(.+)\.tar',
    'http://mirrors\.kernel\.org/gnu/libiconv/libiconv-(.+)\.tar',
]

[MUMPS]
url_regexes = [
    'http://mumps\.enseeiht\.fr/MUMPS_(.+)\.tar',
    'https://mumps-solver\.org/MUMPS_(.+)\.tar',
    'https://graal\.ens-lyon\.fr/MUMPS/MUMPS_(.+)\.tar',

]

[OSQP]
repo = 'https://github.com/osqp/osqp.git'
url_regexes = [
    'https://dl.bintray.com/bstellato/generic/OSQP/(.+)/osqp-'
]

[libogg]
url_regexes = [
    'https://downloads\.xiph\.org/releases/ogg/libogg-(.+)\.tar',
    'https://ftp\.osuosl\.org/pub/xiph/releases/ogg/libogg-(.+)\.tar'
]

[openlibm]
repo = 'https://github.com/JuliaMath/openlibm.git'
url_regexes = [
    'https://github\.com/JuliaMath/openlibm/archive/v(.+)\.tar',
]

[openspecfun]
repo = 'https://github.com/JuliaMath/openspecfun.git'
url_regexes = [
    'https://github\.com/JuliaMath/openspecfun/archive/v(.+)\.tar'
]

[rmath]
repo = 'https://github.com/JuliaStats/Rmath-julia.git'
url_regexes = [
    'https://github\.com/JuliaStats/Rmath-julia/archive/v(.*)\.tar'
]

[spral]
repo = 'https://github.com/ralna/spral.git'

[SuiteSparse]
repo = 'https://github.com/DrTimothyAldenDavis/SuiteSparse.git'
repos = ['https://github.com/Wimmerer/SuiteSparse.git']
url_regexes = [
    'https://github\.com/DrTimothyAldenDavis/SuiteSparse/archive/v(.+)\.tar',
    'http://faculty\.cse\.tamu\.edu/davis/SuiteSparse/SuiteSparse-(.+)\.tar',
]

[Vulkan-Loader]
repo = 'https://github.com/KhronosGroup/Vulkan-Loader.git'

[eudev]
repo = 'https://github.com/eudev-project/eudev'
url_regexes = ['https://dev\.gentoo\.org/~blueness/eudev/eudev-(.+)\.tar']

[fzf]
repo = 'https://github.com/junegunn/fzf.git'

[libblastrampoline]
repo = 'https://github.com/JuliaLinearAlgebra/libblastrampoline.git'
repos = ["https://github.com/staticfloat/libblastrampoline"]

[libdecor]
url_regexes = ['https://gitlab\.freedesktop\.org/libdecor/libdecor/-/archive/(.+)/libdecor-\d']

[libevdev]
repo = 'https://gitlab.freedesktop.org/libevdev/libevdev'

[mtdev]
url_regexes = ['http://bitmath\.org/code/mtdev/mtdev-(.+)\.tar']

[oneTBB]
repo = 'https://github.com/oneapi-src/oneTBB.git'
url_regexes = ['https://github\.com/oneapi-src/oneTBB/archive/refs/tags/v(.+)\.tar']

# Missing projects:
# ASL_jll -- no upstream versioning
# CompilerSupportLibraries_jll -- not yet in jll_metadata
# Enzyme_jll -- not yet in jll_metadata
# FreeType2_jll -- not yet in jll_metadata
# METIS_jll -- not yet in jll_metadata
# MKL_jll -- not yet in jll_metadata
# MUMPS_seq_jll -- not yet in jll_metadata
# MozillaCACerts_jll -- uses a date with hyphens. not really software
# OpenBLAS_jll -- not yet in jll_metadata
# x264_jll -- does not have the proper version number in its URLs
# x265_jll -- not yet in jll_metadata (X/X265/build_tarballs has the wrong case)
