name: Generate and Deploy API

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - 'registration_dates.toml'
      - '.github/workflows/generate-api.yml'
      - 'scripts/generate_api.jl'

jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
            persist-credentials: false

      - name: Install Julia
        uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: '1'

      - name: Install Julia dependencies
        run: |
            julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run the "generate_redirects.jl" Julia script
        run: julia --project=. scripts/generate_api.jl

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: webroot/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5